### ISSUE TITLE
Independence tests for Chain Ladder 

### ISSUE THREAD

**Issue by gig67** [casact/chainladder-python#76]
It is important that some critical assumptions around chain ladder are tested before applying the method. Thomas Mack suggested some tests, for example in "Measuring the variability of Chain Ladder reserve estimates", 1997. 
Below are implementations for tests of correlation among development factors and for the impact of calendar years. I don't feel confident enough to modify the package code directly but hopefully this can be a useful template.

```
def developFactorsCorrelation(df):
    # Mack (1997) test for Correlations between Subsequent Development Factors
    # results should be between -.67x and +.67x stdError otherwise too much correlation
    m1=df.rank() # rank the development factors by column
    m2=df.to_numpy(copy=True) #does the same but ignoring the anti-diagonal
    np.fill_diagonal(np.fliplr(m2),np.nan)
    m2=pd.DataFrame(np.roll(m2,1),columns=m1.columns, index=m1.index).iloc[:,1:] #leave out the first column
    m2=m2.rank()
    numerator=((m1-m2) **2).sum(axis=0)
    SpearmanFactor=pd.DataFrame(range(1,len(m1.columns)+1),index=m1.columns, columns=['colNo'])
    I = SpearmanFactor['colNo'].max()+1
    SpearmanFactor['divisor'] = (I-SpearmanFactor['colNo'])**3 - I +SpearmanFactor['colNo'] #(I-k)^3-I+k
    SpearmanFactor['value']= 1-6*numerator.T/SpearmanFactor['divisor']
    SpearmanFactor['weighted'] = SpearmanFactor['value'] * (I-SpearmanFactor['colNo']-1) / (SpearmanFactor[1:-1]['colNo']-1).sum() #weight sum excludes 1 and I
    SpearmanCorr=SpearmanFactor['weighted'].iloc[1:-1].sum() # exlcuding 1st and last elements as not significant
    SpearmanCorrVar = 2/((I-2)*(I-3))
    return SpearmanCorr,SpearmanCorrVar
```

```
from scipy.stats import binom
def calendarCorrelation(df, pCritical=.1):
    # Mack (1997) test for calendar year effect
    # A calendar period has impact across developments if the probability of the number of small (or large)
    # development factors in that period occurring randomly is less than pCritical
    # df should have period as the row index, on the assumption that the first anti-diagonal is in relation to the same period (development=0) 
    m1=df.rank() # rank the development factors by column
    med=m1.median(axis=0) # find the median value for each column
    m1large=m1.apply(lambda r: r>med, axis=1) # sets to True those elements in each column which are large (above the median rank)
    m1small=m1.apply(lambda r: r<med, axis=1)
    m2large=m1large.to_numpy(copy=True)
    m2small=m1small.to_numpy(copy=True)
    S=[np.diag(m2small[:,::-1],k).sum() for k in range(min(m2small.shape),-1,-1)] # number of large elements in anti-diagonal (calendar year)
    L=[np.diag(m2large[:,::-1],k).sum() for k in range(min(m2large.shape),-1,-1)] # number of large elements in anti-diagonal (calendar year)
    probs=[binom.pmf(S[i], S[i]+L[i], 0.5)+binom.pmf(L[i], S[i]+L[i], 0.5) for i in range(len(S))] # probability of NOT having too many large or small items in anti-diagonal (calendar year)
    return pd.Series([p<pCritical for p in probs[1:]], index=df.index)
```

And using the example in the paper
```
MackEx='''1,2,3,4,5,6,7,8,9
1.6,1.32,1.08,1.15,1.2,1.1,1.033,1,1.01
40.4,1.26,1.98,1.29,1.13,.99,1.043,1.03,
2.6,1.54,1.16,1.16,1.19,1.03,1.026,,
2,1.36,1.35,1.1,1.11,1.04,,,
8.8,1.66,1.4,1.17,1.01,,,,
4.3,1.82,1.11,1.23,,,,,
7.2,2.72,1.12,,,,,,
5.1,1.89,,,,,,,
1.7,,,,,,,,
'''
df=pd.read_csv(StringIO(MackEx), header=0)
df.index = df.index+1 #reindex rows from 1
dfCorr,dfCorrVar = developFactorsCorrelation(df)
print('Development factors correlation is {:.2%}'.format(dfCorr))
print('Factor independence if correlation is in range [{:.2%} to {:.2%}]'.format(-.67*np.sqrt(dfCorrVar),  .67*np.sqrt(dfCorrVar)))
print('Dependence on calendar year:')
print(calendarCorrelation(df))
```
Result is
```
Development factors correlation is 6.96%
Factor independence if correlation is in range [-12.66% to 12.66%]
Dependence on calendar year:
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool
```

**Comment by jbogaardt** [comment]
Thank you @gig67.  These should be very useful and a welcome addition to chainladder!  As they only rely on link ratios, they can be included as additional properties or methods on the Triangle class.  I'll think through how to incorporate in the context of a multidimensional (4D) triangle.

**Comment by gig67** [comment]
Glad to hear that. Feel free to check if the outputs are correct! And thank you again for all the TLC work you are putting in this package.

**Comment by jbogaardt** [comment]
Actually, I would like to give you attribution for the code contribution.  If you're insterested in making a pull request for the basic case, I wouldn't mind merging to get you on the contributor list.  This enhancement wouldn't break anything else so it should be a simple contribution.

We really only need a couple methods in the [core/triangle.py](https://github.com/casact/chainladder-python/blob/master/chainladder/core/triangle.py) file.  Instead of referencing `df`, the functions should just reference `self.link_ratio` or `self.link_ratio.to_frame()` for the simple case.  The Mack example you provided is the raa triangle, so it should test out to your sample when using `cl.load_dataset('raa')`. 

I can certainly go in after merging to improve compatibility with the broader package.  Let me know if you're interested and/or have questions?

**Comment by gig67** [comment]
I appreciate the offer. I have never contributed to a github project so this is a good opportunity for me to learn something. Thanks and stay tuned!

**Comment by jbogaardt** [comment]
Thanks for the contribution.  This is great scaffolding for this much needed functionality.  I think we can get this fully working with the following tasks.  

### Todos:
* [ ] Replace pandas operations with numpy/scipy equivalent and operate on `Triangle.values` to support batch operations for triangles with more than one `index` and/or `column`
* [ ] Consider `dev_to_val`  and work on columns instead of `np.diag` to support asymmetric triangles (e.g. OYDQ)
* [ ] Return type to be `self` with unaltered `index` and `column` properties so that correlation results can be sliced like other `Triangle` objects
* [ ] Use `xp` instead of `np` to make the class work with the `cupy` backend
* [ ] PEP8 compliance on arguments.  Maybe `pCritical` can be `p_critical` or `p_crit`
* [ ] Rename method to have 'test' at end of method name or omit 'test' completely so as not to confuse with `pytest` conventions
* [ ] Add unit tests to [test_triangle.py](https://github.com/casact/chainladder-python/blob/master/chainladder/core/tests/test_triangle.py) - @gig67's original comment has the Mack paper example that can be used.
* [ ] Consider adding to the [stochastic tutorial](https://github.com/casact/chainladder-python/blob/master/docs/tutorials/stochastic-tutorial.ipynb).

It seems like a lot, but its not too bad.  The 1st one is the most challenging.  I can take a crack at these, but if you're interested in any, let me know.

**Comment by aegerton** [comment]
This will be a great enhancement to the package @jbogaardt 

Well done @gig67 !

**Comment by gig67** [comment]
Thanks  @jbogaardt @aegerton,
Being locked down with my biz stuck for now, I can't see anything better than contributing here!
I'll give a try to the To Do list.
- using Triangle.values should not be too difficult. Also, dev_to_val should simplify the process as you say.
- ranking on nd-arrays can be obtained with argsort though need to filter out nans. argsort should work with cupy. The other operations should be easy.
Bear with me.

**Comment by jbogaardt** [comment]
take a look at [this commit](https://github.com/casact/chainladder-python/commit/afb9ae0db7f2154a0c8082197ed01b14df2a95df).  It's my 1st attempt at `calendar_correlation`.  Hope it makes sense.  Still a work in progress as I have not generalized the recursive formula to a 4d triangle.  Not sure how to solve that yet without nested for loops.  I also haven't really done anything on `development_correlation`.  In any case, hope this code helps clarify my bullets above.  I'll leave it in your court for now @gig67, but shout if you need anything.

**Comment by gig67** [comment]
Thanks @jbogaardt and well done. This is going to be a mind-stretch and I fear touching your code.
As per the recursive formula, it can be much simplified into 
```
def pZlower(z,n,p):
    return min(1, 2*binom.cdf(z,n,p))
```
One could quickly build at the start of the function a lookup table T with all the needed values
```
T=[]
for i in range(0,np.max(self.shape[2:]))
    T.append([pZlower2(j,i,0.5) for j in range(0,np.max(self.shape[2:]))])
T=np.array(T)
```
You already have calculated z=min(S,L) and n=S+L so zip(n,z) should be the key to all necessary elements of T
For a simple triangle where n and z are 1-D the list of probabilities would also be 1-D
```
[T[i,j] for i,j in list(zip(n,z))] 
```
I am sure there must be a pythonic way to do so when z, n are 3-D array !

**Comment by jbogaardt** [comment]
Making sure I understand the actuarial side of things. The calendar year test in R's ChainLadder package does not return a vector of calendar period booleans.  It is an evaluation of the entire triangle:
```R
> cyEffTest(RAA)
Calendar Year Effect

Z = 14

95%-Range = ( 8.965613 ; 16.78439 )

Calendar Year Effect: FALSE 
```
From [Mack (1997)](https://www.casact.org/pubs/forum/94spforum/94spf101.pdf) - _It is not advisable to test each Zj separately in order to avoid an accumulation of the error probabilities._

Mack's example follows in a similar fashion to the R's `cyEffTest` function. So, my question is whether there is there precedence for @gig67's approach in a paper somewhere or should we stick close to the Mack paper and the R ChainLadder package.  Feedback would be much appreciated.

**Comment by gig67** [comment]
Thanks for checking this, I am glad that there is critical thinking as well as cross-reference to the R package that I am not familiar with. 
Mack came out with two articles on the subject (that I know of). One in 1993 submitted to CAS (the one you link to) and a later one submitted to the [IFoA (UK) in 1997](https://www.actuaries.org.uk/system/files/documents/pdf/crm2-D6.pdf).
In the latter paper, he revises his approach to the one I implemented. His revised view was that even in the presence of calendar effects, one should reduce the weights (by 50% in his suggestion) but not throw away the data, hence the importance of the individual checks. As he says, "As with every test procedure which is applied several times there is an accumulation of the error probabilities, that is the danger increases that we find a significant case which in reality is not extraordinary. But here, this will not cause any essential disadvantage as we only change weights and do not discard anything entirely." 
This is of course also a matter of personal preferences, including his choice of a 10% confidence level. 
My suggestion would be to add as an extra result or separate function the overall Z measure that you indicated, because it is relevant and for compatibility with the R package. Most of the computation is the same.

**Comment by jbogaardt** [comment]
Thanks for the paper link, and apologies for thinking Mack 1993 is Mack 1997.  Per your suggestion, I think we can add a boolean argument to the method to allow the user to toggle between yearly (1997) vs the overall (1993) approach.  I'll see if I can build the 1993 logic in.

**Comment by jbogaardt** [comment]
There are so many useful properties of these independence tests we may want to see.  I'm thinking it is beneficial to wrap them in classes.  This would expose all their properties (rather than return a tuple from a function) with "dotted" access.  It would make the API look like this:
```python
import chainladder as cl

tri=cl.load_dataset('clrd').groupby('LOB').sum()['CumPaidLoss']

# Access various properties of the tests
tri.development_correlation().spearman_corr 
tri.development_correlation().spearman_corr_var 

tri.valuation_correlation(p_critical=.05).z_critical
```
The [latest commit](https://github.com/casact/chainladder-python/commit/b199044f4af26a56047dddd4ae02424b385b425d) includes these classes and makes the above functionality valid.  Not sure that these are the best names for these methods and properties (we can easily change them to whatever makes sense).  But, I do like this setup better because we can expose any property of these tests we want in a clean way.

**Comment by gig67** [comment]
Great, so this package leaps-frog R :-)

In respect of my previous

> ```
>[T[i,j] for i,j in list(zip(n,z))] 
>```
>I am sure there must be a pythonic way to do so when z, n are 3-D array !

The answer is probably as simple as
 ```
T[n,z] 
```
which gives out very quickly an array with same shape as n and z

**Comment by jbogaardt** [comment]
> The answer is probably as simple as
> 
> ```
> T[n,z] 
> ```
> 
> which gives out very quickly an array with same shape as n and z

Let's add that in as its currently sitting on a nested loop.

**Comment by jbogaardt** [comment]
I've reviewed the papers as well as the R implementation of the same, and using those, decided on a naming convention for test attributes that feels reasonable.

The `Triangle` class has two additional methods `development_correlation` and `valuation_correlation` which return objects of type [DevelopmentCorrelation](https://chainladder-python.readthedocs.io/en/latest/modules/generated/chainladder.DevelopmentCorrelation.html#chainladder.DevelopmentCorrelation) and [ValuationCorrelation](https://chainladder-python.readthedocs.io/en/latest/modules/generated/chainladder.ValuationCorrelation.html#chainladder.ValuationCorrelation) (links reference the docs of the classes).  Per @gig67 's suggestion, the valuation test takes an additional argument `total` which is a boolean representing whether the test should be applied to the triangle in total (True) or to each individual calendar year.

People are free to use the methods or the classes directly.  For example, the following are equivalent:
```python
import chainladder as cl
cl.load_dataset('raa').development_correlation(p_critical=0.1)
cl.DevelopmentCorrelation(cl.load_dataset('raa'), p_critical=0.1)
```
Still haven't optimized nested for loop if you want to take a look at that one, but at least what we have works.  The other remaining item is putting examples in the docs, but that shouldn't stop it from making it into the next release.  If you see anything missing, let me know, otherwise, I'll look to releasing this in the next few days.

**Comment by gig67** [comment]
Hi @jbogaardt congratulations on your many progresses here. 
I just wanted to let you know that I have been trying to be helpful but I struggle. 
To avoid messing up my local machine, I decided the cleanest way was to use Google Colab
```
!git clone --single-branch --branch CL-independence-tests  https://github.com/gig67/chainladder-python.git   # or similar
!cd chainladder-python
!python setup.py develop

import chainladder as cl
```
Unfortunately the last command throws ModuleNotFoundError: No module named 'xlcompose' even if the module has apparently been installed. 
Until I find a good step-by-step guide to updating packages locally / on colab without messing up my proper install I can only sit idle and give comments on the sides...

**Comment by jbogaardt** [comment]
I think you can just do the following in colab:
`!pip install git+https://github.com/casact/chainladder-python/` and you should get all dependencies resolved.

**Comment by gig67** [comment]
Great, thanks a lot! Maybe I'm getting there! then if I replace any file such as [...] I should see the immediate result change because it is interpreted, hopefully.

I just did a test on your package
```
raa=cl.load_dataset('raa')
raa.valuation_correlation(p_critical=.1, total=False).z.values
```
and the output is: array([[14.]])
I was expecting a list of years and probabilities, am I wrong?

**Comment by jbogaardt** [comment]
Oops, thats a bug.  I didn't pass through the `total` argument from the function.  So it always defaults to `total=True` regardless of what you put in.  I'll fix that.  Not sure I have the naming down pat.  The boolean vectors for years would be under `z_critical`, probabilities are under `probs`

**Comment by gig67** [comment]
> I think you can just do the following in colab:
> !pip install git+https://github.com/casact/chainladder-python/ 
> and you should get all dependencies resolved.

Turned out a bit more complex, but now it works
```
!pip3 install -e git+https://github.com/casact/chainladder-python.git#egg=chainladder 
import sys
sys.path.append('/content/src/chainladder')
```
Then modify files as needed in /content/src/chainladder , and run 
```import chainladder as cl```
Whenever code is modified again, restart runtime and do the import again (no need to re-install)

This way I fixed the code with the T lookup table, will upload soon.
More importantly, I think I can be of a bit more help for the future.

**Comment by gig67** [comment]
Hopefully you can see my latest commit and check it!
https://github.com/gig67/chainladder-python/commit/327b18226cfef8659bafe75eac47635056a796f9

**Comment by gig67** [comment]
Added some explanatory text at the start of the development tutorial
https://github.com/gig67/chainladder-python/commit/a68f122d119733d35709f716a2b6911e27629c53

**Comment by jbogaardt** [comment]
That's a pretty neat trick on setting up a developer environment in colab.  Very useful.

The code update is cleaner without a triple `for` loop.  However, I get an index error when applying to the 'clrd' dataset whereas the original plowed through with only warnings.
```python
cl.load_sample('clrd').valuation_correlation(total=False)
``` 
I think the failure happens on a completely empty triangle and we shouldn't be really testing an empty triangle anyway.  However, in the context of many triangles, it may be better to return nans for the bad triangle then to fail on the entire object.

Nice work on the tutorial - can merge that when you do a pull request.

**Comment by gig67** [comment]
Error with clrd example was linked to the T lookup table not being sufficiently large - fixed that in new commit: 
https://github.com/casact/chainladder-python/pull/79/commits/cb38d03c639740a3b7063cfbc9ee4daf5ffe41ad 

clrd now shows about 8% of triangles where at least one valuation year has some significant correlation
```
np.count_nonzero(clrd_val_corr.z_critical.values.sum(axis=3))/(775*6)
# result is 0.081
```

**Comment by jbogaardt** [comment]
Thanks for the latest fixes @gig67.  I think this one is done now.  I'll push a new release to pypi to make the enhancement available in the official package.

**Comment by udaykumarravada** [comment]
i am testing the assumptions of mack chain ladder method and for my triangle both assumptions didn't meet. 
Does it mean that the estimators we calculated from the chain ladder are no longer BLUE and what to do in these situations?

**Comment by gig67** [comment]
> i am testing the assumptions of mack chain ladder method and for my triangle both assumptions didn't meet. Does it mean that the estimators we calculated from the chain ladder are no longer BLUE and what to do in these situations?

Always double check my answers but BLUE estimators require independence and homoscedasticity of residuals which, if the Mack tests fail due to correlations being found both across cohorts and within the same cohort, probably will not happen. When the Mack conditions are not respected, rather than Chain-Ladder one should probably look at forecasting through autoregressive models such as AR(I)MA.

**Comment by udaykumarravada** [comment]
Can you please post any know literatures about using TSM models in for reserving concepts if in case chain ladder fails?
